<?php

/**
 * @file
 * Contains d8_cache.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function d8_cache_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the d8_cache module.
    case 'help.page.d8_cache':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Cache API') . '</p>';
      return $output;

    default:
  }
}
 
/**
 * Implements hook_theme().
 */
function d8_cache_theme($existing, $type, $theme, $path) {
   return array('d8cacheblock' =>                  // this is the name of the template
           array(
            'variables' => array(
                'title' => 'Default title',
                'nodetitle' => null,
            ),
        )
    );
}
