<?php

/**
 * @file
 * Contains event_subscriber_demo.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\event_subscriber_demo\Event\EntityUpdateEvent;

/**
 * Implements hook_help().
 */
function event_subscriber_demo_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the event_subscriber_demo module.
    case 'help.page.event_subscriber_demo':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Demo of creating and subscribing to events') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_entity_update().
 */
function event_subscriber_demo_entity_update(Drupal\Core\Entity\EntityInterface $entity) {
  \Drupal::service('event_dispatcher')->dispatch(EntityUpdateEvent::ENTITY_UPDATE, new EntityUpdateEvent($entity));
  $entityID = $entity->id();
  $entityType = $entity->getEntityTypeId();
  //dump($entityType.':'.$entityID);
  //SET REQUEST TIME
  $request_time = REQUEST_TIME;
  $request_time = date(DATE_RFC822, $request_time);
  \Drupal::state()->set('entity_update_hook',$request_time);
  \Drupal::state()->set('entity_update_type',$entityType);
  \Drupal::state()->set('entity_update_id',$entityID);
}