<?php

/**
 * @file
 * Contains d8_cache.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function latest_feeds_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the latest_feeds module.
    case 'help.page.latest_feeds':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Creating a block which shows latest updated posts.') . '</p>';
      return $output;

    default:
  }
}
